### ISSUE TITLE
My first crack at B2C Node Web API Sample

### ISSUE THREAD

**Issue by dstrockis** [AzureADQuickStarts/B2C-WebApi-Nodejs#2]
Tried to go through the walk through to get my Node server running for the iOS walk through.  Here are my notes, we can go through them whenever.
### Improvements/Questions
- Why do I enter `http://localhost/TodoListService` as reply URL?
- Why do I create a client secret?
- Why do I have to create policies in the API? Shouldn't I only do that in the client?
- Do I need to run mongod in addition to installing it?
- The directions say to create the `azuread` directory, but the skeleton already has the `node-server` directory...
- Directions say to create `server.js`, but there's already `app.js`
- Is there a better way than npm installing everything?
- Comma missing in config.js
- What is the `audience` used for in config?
- What keys are you using to validate? How is the `/common` metadata endpoint working for B2C?
- Indentation is not maintained on ACOM
- Step 18, 19, 18
- Step 19 fails to re-run server with:

```
TypeError: OIDCBearerStrategy is not a function
    at Object.<anonymous> (/Users/Strockis/Source/AzureADQuickStarts/B2C-WebApi-Nodejs/node-server/app.js:283:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```
- General comment: It's like 80% Node setup, and 20% identity stuff
- General comment: Do we really need 20 steps to get this thing going? It's overwhelming.
- General comment: Maybe the iOS sample should not link to this article, but rather in-line the shortcut steps to getting the completed Node sample up and running.  Not every iOS developer will want to read this whole thing to complete the iOS QuickStart
### Things I did like:
- The step numbers in skeleton code comments matched the docs
- The expected output when I ran npm install

**Comment by Jtango18** [comment]
I've just submitted a pull request that address a bunch of these issues. :-)

**Comment by dstrockis** [comment]
Hey, thanks @Jtango18! That's awesome.  Could you post a link to the PR though? I can't seem to find it.

@brandwe do you want to have a look when JT shares the link?

**Comment by Jtango18** [comment]
@brandwe is across it. I made one small mistake that needed to be remedied this morning before he can merge it.

Link is here: https://github.com/Azure/azure-content/pull/5024

**Comment by dstrockis** [comment]
Ah, ok cool.  Thanks again!

**Comment by Jtango18** [comment]
I love this product and I'm enjoying the hell out of being a part of the community around it. My first contributions and accepted pull requests have all been attached to B2C projects!

**Comment by dstrockis** [comment]
Haha, beautiful.  If/when you have ideas for improvements @brandwe and I are your guys.

**Comment by Jtango18** [comment]
Good to know.

I've hit a rather nasty big that @brandwe is looking in to for me at the moment. Once that's sorted I've got a few more contribs to make, particularly around the iOS project.

Spreading the good word at a local user group presentation soon too!

**Comment by jmprieur** [comment]
Closing this issue as we are archiving this sample
