### ISSUE TITLE
Default Port and Instant Unauthorized response

### ISSUE THREAD

**Issue by tence** [AzureADQuickStarts/B2C-WebApi-Nodejs#3]
The node listens to port 3000 by default, so you should call **http://localhost:3000/tasks** after startup. (README states port 8888 currently)

After I open **http://localhost:3000/tasks** I get a 401 Unauthorized instantly.
I expected to get redirected or at least some deeper log info whats going wrong.

Could you give me a hint how to proceed please?
Thanks!

**Comment by jmprieur** [comment]
Closing this issue as we are archiving this sample
